// Auto-generated by openapi-typescript
// Run: pnpm run codegen

export interface Conversation {
  id: string;
  title: string;
  created_at: string;
  updated_at: string;
}

export interface Message {
  id: string;
  conversation_id: string;
  role: 'user' | 'assistant';
  content: string;
  status: 'complete' | 'interrupted';
  created_at: string;
}

export interface ToolParameter {
  name: string;
  type: string;
  description: string;
  required: boolean;
  default?: any;
  enum?: string[];
}

export interface Tool {
  id: string;
  name: string;
  description: string;
  parameters: ToolParameter[];
}

// OpenAPI paths type (placeholder - will be auto-generated)
export type paths = {
  '/api/conversations/': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': Conversation[];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          'application/json': { title?: string };
        };
      };
      responses: {
        200: {
          content: {
            'application/json': Conversation;
          };
        };
      };
    };
  };
  '/api/conversations/{conversation_id}': {
    get: {
      parameters: {
        path: { conversation_id: string };
      };
      responses: {
        200: {
          content: {
            'application/json': Conversation;
          };
        };
      };
    };
    patch: {
      parameters: {
        path: { conversation_id: string };
      };
      requestBody: {
        content: {
          'application/json': { title: string };
        };
      };
      responses: {
        200: {
          content: {
            'application/json': Conversation;
          };
        };
      };
    };
    delete: {
      parameters: {
        path: { conversation_id: string };
      };
      responses: {
        204: never;
      };
    };
  };
};
